version: '3.9'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tokobot
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes: 
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - backend
  nsqlookupd:
    image: nsqio/nsq
    ports:
      - 4160:4160
      - 4161:4161
    command: /nsqlookupd
    networks: 
      - backend
  nsqd:
    image: nsqio/nsq
    ports:
      - 4150:4150
      - 4151:4151
    depends_on:
      - nsqlookupd
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=nsqd
    networks: 
      - backend
  nsqadmin:
    image: nsqio/nsq
    ports:
      - 4171:4171
    depends_on:
      - nsqlookupd
      - nsqd
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    networks: 
      - backend
  bot:
    build:
      context: .
    restart: always
    image: tokobot
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  postgres-volume:

networks: 
  backend:
